Repository AY2223S1-CS2103T-T12-4/tp, pull requests merged in 2022-10, with the labels that each got.

#109 Add full stops to use cases in developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#97 Reorder feature sections in User Guide
  docs/UserGuide.md
Labels: type.Task

#124 Feature delete task
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#164 Update UG to use new command syntax
  docs/UserGuide.md
Labels: priority.High

#182 Enable assertions
  build.gradle
Labels: type.Task

#194 Bugfix for add tasks
  src/main/java/seedu/uninurse/logic/commands/PatientsTodayCommand.java
  src/main/java/seedu/uninurse/logic/parser/AddTaskCommandParser.java
Labels: type.Bug

#200 Add use cases for patients today and tasks on a day to the DG
  docs/DeveloperGuide.md
Labels: type.Docs

#208 Add undo and redo command
  src/main/java/seedu/uninurse/commons/core/Config.java
  src/main/java/seedu/uninurse/logic/LogicManager.java
  src/main/java/seedu/uninurse/logic/commands/AddGenericCommand.java
  src/main/java/seedu/uninurse/logic/commands/ClearCommand.java
  src/main/java/seedu/uninurse/logic/commands/Command.java
  src/main/java/seedu/uninurse/logic/commands/DeleteGenericCommand.java
  src/main/java/seedu/uninurse/logic/commands/EditGenericCommand.java
  src/main/java/seedu/uninurse/logic/commands/RedoCommand.java
  src/main/java/seedu/uninurse/logic/commands/UndoCommand.java
  src/main/java/seedu/uninurse/logic/commands/UndoableCommand.java
  src/main/java/seedu/uninurse/logic/parser/UninurseBookParser.java
  src/main/java/seedu/uninurse/model/Model.java
  src/main/java/seedu/uninurse/model/ModelManager.java
  src/main/java/seedu/uninurse/model/PersistentUninurseBook.java
  src/main/java/seedu/uninurse/model/UninurseBookSnapshot.java
  src/test/java/seedu/uninurse/logic/commands/AddPatientCommandTest.java
Labels: priority.High

#217 Update version number to v1.3
  src/main/java/seedu/uninurse/MainApp.java
Labels: priority.High

#212 Fix task list indexing issue
  src/main/java/seedu/uninurse/model/task/TaskList.java
Labels: type.Bug, severity.Medium

#216 Update UG and DG relating to `undo`, `redo`, and `clear` commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Docs

#231 Update DG with implementation of undo/redo feature
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UndoSequenceDiagram.png
Labels: type.Docs

#229 Docs: Add basic skeleton for implementation of add condition feature
  docs/DeveloperGuide.md
  docs/diagrams/AddConditionActivityDiagram.puml
  docs/diagrams/AddConditionSequenceDiagram.puml
  docs/images/AddConditionActivityDiagram.png
  docs/images/AddConditionSequenceDiagram.png
Labels: type.Docs

#230 Add implementation of `listTask` and `viewTask` to DG
  docs/DeveloperGuide.md
  docs/diagrams/ListTaskSequenceDiagram.puml
  docs/diagrams/ViewTaskSequenceDiagram1.puml
  docs/diagrams/ViewTaskSequenceDiagram2.puml
  docs/images/ListTaskSequenceDiagram.png
  docs/images/ViewTaskSequenceDiagram1.png
  docs/images/ViewTaskSequenceDiagram2.png
Labels: type.Docs

#236 Fix command type standardization
  src/main/java/seedu/uninurse/logic/commands/AddConditionCommand.java
  src/main/java/seedu/uninurse/logic/commands/AddPatientCommand.java
  src/main/java/seedu/uninurse/logic/commands/AddTaskCommand.java
  src/main/java/seedu/uninurse/logic/commands/ClearCommand.java
  src/main/java/seedu/uninurse/logic/commands/CommandResult.java
  src/main/java/seedu/uninurse/logic/commands/CommandType.java
  src/main/java/seedu/uninurse/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/uninurse/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/uninurse/logic/commands/EditPatientCommand.java
  src/main/java/seedu/uninurse/logic/commands/EditTaskCommand.java
  src/main/java/seedu/uninurse/logic/commands/ExitCommand.java
  src/main/java/seedu/uninurse/logic/commands/FindCommand.java
  src/main/java/seedu/uninurse/logic/commands/HelpCommand.java
  src/main/java/seedu/uninurse/logic/commands/ListCommand.java
  src/main/java/seedu/uninurse/logic/commands/ListTaskCommand.java
  src/main/java/seedu/uninurse/logic/commands/PatientsTodayCommand.java
  src/main/java/seedu/uninurse/logic/commands/RedoCommand.java
  src/main/java/seedu/uninurse/logic/commands/UndoCommand.java
  src/main/java/seedu/uninurse/logic/commands/ViewTaskCommand.java
  src/test/java/seedu/uninurse/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/uninurse/logic/commands/AddConditionCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/ClearCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/CommandTestUtil.java
  src/test/java/seedu/uninurse/logic/commands/DeletePatientCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/ExitCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/FindCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/HelpCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/ListCommandTest.java
  src/test/java/seedu/uninurse/logic/commands/PatientsTodayCommandTest.java
Labels: priority.High

#234 Doc: Update user guide with condition and tag features
  docs/UserGuide.md
Labels: type.Docs

#248 Fix GUI update for `addCondition` command
  src/main/java/seedu/uninurse/logic/commands/AddConditionCommand.java
Labels: priority.High

#249 Feature: view patient
  src/main/java/seedu/uninurse/logic/commands/CommandResult.java
  src/main/java/seedu/uninurse/logic/commands/CommandType.java
  src/main/java/seedu/uninurse/logic/commands/ViewPatientCommand.java
  src/main/java/seedu/uninurse/logic/parser/UninurseBookParser.java
  src/main/java/seedu/uninurse/logic/parser/ViewPatientCommandParser.java
  src/main/java/seedu/uninurse/model/ModelManager.java
  src/main/java/seedu/uninurse/model/exceptions/PatientOfInterestNotFoundException.java
  src/main/java/seedu/uninurse/ui/MainWindow.java
  src/main/java/seedu/uninurse/ui/OutputPanel.java
  src/test/java/seedu/uninurse/logic/commands/ViewPatientCommandTest.java
  src/test/java/seedu/uninurse/logic/parser/ViewPatientCommandParserTest.java
Labels: priority.High

#258 Fix bug in PR merge
  src/test/java/seedu/uninurse/logic/commands/EditTaskCommandTest.java
Labels: priority.High, severity.High

#250 Improve `find` command keyword-matching
  src/main/java/seedu/uninurse/commons/util/StringUtil.java
  src/main/java/seedu/uninurse/logic/commands/FindCommand.java
  src/main/java/seedu/uninurse/logic/parser/CliSyntax.java
  src/main/java/seedu/uninurse/logic/parser/FindCommandParser.java
  src/main/java/seedu/uninurse/model/condition/ConditionContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/medication/MedicationContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/person/PatientContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/person/PatientMatchPredicate.java
  src/main/java/seedu/uninurse/model/person/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/tag/TagContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/task/TaskContainsKeywordsPredicate.java
  src/test/java/seedu/uninurse/logic/commands/CommandTestUtil.java
  src/test/java/seedu/uninurse/logic/commands/FindCommandTest.java
  src/test/java/seedu/uninurse/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/uninurse/logic/parser/UninurseBookParserTest.java
  src/test/java/seedu/uninurse/model/ModelManagerTest.java
Labels: priority.High

#261 Update UG for `find`, `clear`, `undo`, and `redo` commands
  docs/UserGuide.md
Labels: type.Docs

#263 Feature UI - show DateTime for viewTask
  src/main/java/seedu/uninurse/model/task/DateTime.java
  src/main/java/seedu/uninurse/ui/TaskListCard.java
Labels: type.Gui

#265 Fix missing DeleteTagCommandParser case
  src/main/java/seedu/uninurse/logic/parser/UninurseBookParser.java
Labels: type.Bug

#269 Fix window size of RedoCard
  src/main/resources/view/RedoCard.fxml
Labels: type.Bug

#284 Doc: update DG use cases for conditions and tags
  docs/DeveloperGuide.md
Labels: type.Docs

#293 Refine updated patient card
  src/main/java/seedu/uninurse/ui/UpdatedPatientCard.java
  src/main/resources/view/Theme.css
  src/main/resources/view/UpdatedPatientCard.fxml
Labels: type.Gui

#294 Remove instance of updateFilteredPersonList in DeleteTask and wrap name text in ScheduleListCard
  src/main/java/seedu/uninurse/logic/commands/DeleteTaskCommand.java
  src/main/resources/view/ScheduleListCard.fxml
  src/test/java/seedu/uninurse/logic/commands/DeleteTaskCommandTest.java
Labels: type.Bug

#295 Integrate new commands to `*GenericCommandParser`
  src/main/java/seedu/uninurse/logic/commands/DisplayTasksGenericCommand.java
  src/main/java/seedu/uninurse/logic/commands/ListTaskCommand.java
  src/main/java/seedu/uninurse/logic/commands/PatientsTodayCommand.java
  src/main/java/seedu/uninurse/logic/commands/TasksOnCommand.java
  src/main/java/seedu/uninurse/logic/commands/ViewPatientCommand.java
  src/main/java/seedu/uninurse/logic/commands/ViewTaskCommand.java
  src/main/java/seedu/uninurse/logic/parser/AddGenericCommandParser.java
  src/main/java/seedu/uninurse/logic/parser/CliSyntax.java
  src/main/java/seedu/uninurse/logic/parser/DeleteGenericCommandParser.java
  src/main/java/seedu/uninurse/logic/parser/DisplayTasksGenericCommandParser.java
  src/main/java/seedu/uninurse/logic/parser/EditGenericCommandParser.java
  src/main/java/seedu/uninurse/logic/parser/ParserUtil.java
  src/main/java/seedu/uninurse/logic/parser/UninurseBookParser.java
  src/main/java/seedu/uninurse/logic/parser/ViewPatientCommandParser.java
  src/main/java/seedu/uninurse/logic/parser/ViewTaskCommandParser.java
  src/test/java/seedu/uninurse/logic/parser/ViewPatientCommandParserTest.java
Labels: priority.High

#301 Fix outdated styling of help window and update MESSAGE_USAGE for conditions and tags
  src/main/java/seedu/uninurse/logic/commands/AddConditionCommand.java
  src/main/java/seedu/uninurse/logic/commands/AddTagCommand.java
  src/main/java/seedu/uninurse/logic/commands/DeleteConditionCommand.java
  src/main/java/seedu/uninurse/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/uninurse/logic/commands/EditConditionCommand.java
  src/main/java/seedu/uninurse/logic/commands/EditTagCommand.java
  src/main/java/seedu/uninurse/logic/commands/ViewPatientCommand.java
  src/main/java/seedu/uninurse/ui/ModifiedPatientCard.java
  src/main/java/seedu/uninurse/ui/UpdatedPatientCard.java
  src/main/resources/view/HelpWindow.css
Labels: priority.High

#304 Add `Remark` keyword-matching to `find` command
  src/main/java/seedu/uninurse/model/person/PatientContainsKeywordsPredicate.java
  src/main/java/seedu/uninurse/model/person/PatientMatchPredicate.java
  src/main/java/seedu/uninurse/model/remark/RemarkContainsKeywordsPredicate.java
Labels: priority.High

#303 Add missing v1.3 features to UG
  docs/UserGuide.md
Labels: priority.High, type.Docs

#305 Fix options-based command syntax limit
  src/main/java/seedu/uninurse/logic/parser/ParserUtil.java
Labels: severity.Medium

#307 Update edit task feature in UG
  docs/UserGuide.md
Labels: priority.High

#366 Reorganise sections in UG
  docs/UserGuide.md
Labels: type.Docs
